name: Build YTLite Deb from Source

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-deb:
    name: Build YTLite Deb
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Dependencies
        run: brew install make ldid dpkg

      - name: Set PATH environment variable
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV

      - name: Cache Theos
        id: theos
        uses: actions/cache@v5
        env:
          cache-name: theos_cache_9bc7340
        with:
          path: theos/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Setup Theos
        if: steps.theos.outputs.cache-hit != 'true'
        uses: actions/checkout@v6
        with:
          repository: theos/theos
          ref: 9bc73406cf80b711ef4d02c15ff1dedc4478a275
          path: theos
          submodules: recursive

      - name: Download iOS SDK
        if: steps.theos.outputs.cache-hit != 'true'
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
          git checkout
          mv *.sdk $THEOS/sdks

      - name: Clone Headers
        run: |
          if [ -d "$THEOS/include/YouTubeHeader" ]; then
            cd $THEOS/include/YouTubeHeader && git pull
          else
            cd $THEOS/include && git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeHeader.git
          fi
          if [ -d "$THEOS/include/PSHeader" ]; then
            cd $THEOS/include/PSHeader && git pull
          else
            cd $THEOS/include && git clone --quiet --depth=1 https://github.com/PoomSmart/PSHeader.git
          fi

      - name: Build YTLite from source
        run: |
          make clean package DEBUG=0 FINALPACKAGE=1

      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ytlite-deb
          path: packages/*.deb
          if-no-files-found: error
          retention-days: 7
